Closes #66 - Rework Maintenance settings
zammad/zammad-admin-documentation pull request #151
Opened 2022-05-22 13:40 UTC by MrGeneration

This PR reworks the maintenance setting texts, replaces screenshots and describes the modals better.

2022-06-07 09:44 UTC, YetAnotherGerrit requested changes

2022-06-07 09:44 UTC, YetAnotherGerrit commented on system/maintenance.rst
> +      Selecting this option will change the messages acceptance button from
"message" instead of "messages".

2022-06-07 09:44 UTC, YetAnotherGerrit commented on system/maintenance.rst
> +      *Close* (with nothing happening) to *Continue session* which forces
"to *Continue session*, which forces" instead of "to *Continue session* which forces".

2022-06-07 09:44 UTC, YetAnotherGerrit commented on system/maintenance.rst
> +      .. tab:: without reload application
Suggestion: add "Example". Also start header with capital letter.
"Example without reload application" instead of "without reload application".

2022-06-07 09:44 UTC, YetAnotherGerrit commented on system/maintenance.rst
> +      .. tab:: with reload application
Suggestion: add "Example". Also start header with capital letter.
"Example with reload application" instead of "with reload application".

2022-06-07 10:59 UTC, MrGeneration commented
Please have a look if it's fitting now.

2022-06-09 11:42 UTC, YetAnotherGerrit approved these changes

2022-06-09 11:47 UTC, merged