Draft: added pgp integration (#264)
zammad/zammad-admin-documentation pull request #265
Opened 2023-07-24 12:00 UTC by ralf401

2023-07-24 12:52 UTC, dvuckovic requested changes

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/index.rst
> +   pgp/index
Could we please reorder the list of these integrations alphabetically? It's becoming too long to reliable identify topic of interest. Feel free to apply the same reasoning to other integrations block if you wish.

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +PGP is another method for secure email communication.
Let's define PGP acronym before we use it for the first time (i.e. `Pretty Good Privacy (PGP) is...`).

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +   is a proof that a message hasn’t been manipulated on it's way.
`it's` => `its`

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +   In other words, it guarantees a message’s **integrity** and **authenticity**.
`a message's` => `message`

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +   In other words, it guarantees **privacy** and **data security**.
Let's add `message` subject before `privacy and data security`.

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +To use the pgp function, you fist have to enable the integration (PGP).
`pgp` should be used uppercase only since it's an acronym.

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +When you swith the toggle to *enabled*, you can add keys by clicking the *add key* button.
`swith` => `switch`

The second part of the sentence is not completely correct: admins can manage keys *without* enabling the feature first. Actually, sometime this is preferred :) Perhaps we can simply avoid making connection to the switch, and separate these into two sentences instead?

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +   For **checking the signature** of signed *incoming* emails, you have to import the public key of the sender.
`checking` => `verifying`

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +   For **decrypting** of encrypted *incoming* emails, you have to import the public key of the sender.
Hm, not exactly: **private** key of the system sender (in this case "recipient", since it's incoming) must be present.

2023-07-24 12:52 UTC, dvuckovic commented on images/system/integrations/pgp/paste_key.png
We should redact the first two lines of the private key hash, since it can be considered somewhat sensitive. I understand it's a test key anyway, however we might receive some bug reports due to this being present in original form.

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +
We should mention here that the system supports importing keys in ASCII-armor format as well as binary GPG format (they are converted on-the-fly). Basically any GPG supported key format is supported in this place.

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +
Here we should mention only ASCII-armor format is supported while pasting. While it should be obvious, you never know™

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +If you want to download your keys, you can do this as well in the corresponding actions button.
`in the corresponding actions button` => `via corresponding action buttons`

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +Here you can see the last actions regarding signing and encryption and if they were succesfull.
`successfull` => `successful`

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +   You can create them yourself! Please have a look :doc:`here </system/integrations/pgp/generate_keys>` for details.
I recommend we remove this part completely. The guide was written with devs in mind only, and it should not be done in this way.

There are many guides out there to generate PGP keys, we can just think about linking to some of them or simply state that the keys are a prerequisite to use this feature.

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +**It says a passphrase is needed, but I haven't one.**
`haven't one` => `haven't got one`

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +   If the key is secured with a passphrase, you have to provide it for the import in Zammad.
Please mention that a key may have an empty passphrase, although it's not recommended.

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +   Your customer also has to configure PGP in his email workflow and import your public key.
Should we also mention that the customer's public keys must be obtained in advance too and imported manually?

2023-07-24 12:52 UTC, dvuckovic commented on system/integrations/pgp/generate_keys.rst
We should drop this file, see below for reasoning.

2023-07-26 07:54 UTC, ralf401 commented
Hi @dvuckovic,

this merge request is still blocked. Have I overlooked something or did you not review it so far? Thanks!

2023-07-26 08:07 UTC, dvuckovic requested changes

2023-07-26 08:07 UTC, dvuckovic commented on images/system/integrations/pgp/integration_pgp.png
Could you please redo this screenshot against the `demo-chrispresso` instance? It has a nicer left sidebar and avatar (not so empty).

2023-07-26 08:07 UTC, dvuckovic commented on images/system/integrations/pgp/pgp_ticket_creation.png
Same here!

2023-07-26 08:07 UTC, dvuckovic commented on system/integrations/pgp/index.rst
> +   public key of the customer.
`public key of the customer` => `private key of your Zammad email account`

2023-07-26 09:51 UTC, dvuckovic approved these changes

2023-07-26 10:01 UTC, merged