Replaced screenshots for triggers
zammad/zammad-admin-documentation pull request #279
Opened 2023-08-07 13:14 UTC by ralf401

2023-08-07 13:41 UTC, dvuckovic requested changes

2023-08-07 13:41 UTC, dvuckovic commented on images/manage/organizations/general-view-of-a-busy-organization.png
The new screenshot seems a tad bit too large: let's recreate it in 1280x720 max.

2023-08-07 13:41 UTC, dvuckovic commented on images/manage/trigger/move-tickets-of-specific-customer-to-specific-group.png
Same here: the dialog seems a bit too large.

2023-08-07 13:41 UTC, dvuckovic commented on images/manage/trigger/trigger-based-auto-replies-on-follow-ups.png
Size again.

2023-08-07 13:41 UTC, dvuckovic commented on images/manage/trigger/trigger-based-priotize-change.png
Size + typo in the filename.

2023-08-07 14:06 UTC, ralf401 commented on images/manage/organizations/general-view-of-a-busy-organization.png
Oh it looks like my already smaller screenshot was overwritten somehow :-O

I just wanted to show the same information as before, but I think here it is no problem to limit it to 1280x720. Then the list of open / closed tickets will only show the title.

I re-upload it.

2023-08-07 14:12 UTC, MrGeneration commented on images/manage/trigger/move-tickets-of-specific-customer-to-specific-group.png
Just my two cents:
There are several places in the documentations where you'll find screenshots that are drastically larger than the readme's limit at least for one side of the image. For the exact reason Ralf mentioned. When it was necessary information are shown, I usually used higher resolutions to overcome this or started to cut away uneeded UI parts like the tab bar (especially for triggers)

2023-08-07 14:33 UTC, dvuckovic commented on images/manage/trigger/move-tickets-of-specific-customer-to-specific-group.png
I totally agree that in some cases the height of the screenshot has to be longer, however I would still try to create it against the width of 1280px. If we did our job correctly, all important elements should be contained in this width, and then the length only can be longer so everything of note is contained within.

As @MrGeneration mentioned, it's perfectly fine to screenshot just the relevant node (in this case a dialog), including the "chrome" of the app around it does not bear any purpose.

2023-08-07 14:53 UTC, ralf401 commented on images/manage/trigger/move-tickets-of-specific-customer-to-specific-group.png
I reduced it already, just showing the modal window and width is <1280px. So I will leave it as uploaded. I will double check the other ones, why they are different in width (not 1175px) and re-upload if necessary.

2023-08-07 14:59 UTC, ralf401 commented on images/manage/trigger/trigger-based-auto-replies-on-follow-ups.png
Recreated screenshot. You are right, the modal was created without the limitation on 1280 in width.

2023-08-08 07:18 UTC, dvuckovic approved these changes

2023-08-08 07:54 UTC, merged