Draft: Fixes #496 - Added date/time variable explanation
zammad/zammad-admin-documentation pull request #508
Opened 2024-03-18 15:57 UTC by ralf401

2024-03-19 08:23 UTC, fliebe92 commented on system/variables.rst
> +     -
This could be removed I guess. :D

2024-03-19 08:37 UTC, fliebe92 commented on system/variables.rst
> +| ``#{dt(ticket.updated_at, "%A, %Y-%m-%d %H:%M (Europe/Berlin)", "Europe/Berlin")}``
TODO: Explain the format string

2024-03-19 08:38 UTC, fliebe92 commented on system/variables.rst
> +in combination with a date/time variable.
TODO: The `dt` method could be used ...

2024-03-19 08:38 UTC, fliebe92 commented on system/variables.rst
> +     -
TODO: Remove

2024-03-19 08:39 UTC, fliebe92 requested changes
Great work, thanks! Only some small changes are required.

2024-03-22 08:53 UTC, tschaefer approved these changes

2024-03-22 09:03 UTC, fliebe92 approved these changes

2024-03-22 09:04 UTC, merged