Enhance information regarding notification channel
zammad/zammad-admin-documentation pull request #74
Opened 2020-09-22 10:19 UTC by MrGeneration

Up to now the documentation doesn't declare a notification channel being dependent on the notification sender address.
This leads to confusion on new members especially in situations where you start using SMTP which restrictive mail servers that only allow specific mail addresses per user.

This pull request adds a direct hint within the channel notification detail dialogue.
Also, earlier the wording for email notification channels on the overview page was stating this channel being relevant for "auto-replies" which is miss leading. This is why I replaced it with a more fitting wording.

2020-10-13 06:45 UTC, rlue requested changes
Just the one suggestion. Sorry it took so long to get back to you!

2020-10-13 06:45 UTC, rlue commented on channels/email/accounts/email-notification.rst
> +   .. hint:: The notification sender address can be configured within the :doc:`Settings tab <../settings>`.
```suggestion
   .. hint:: The “From:” address on system notifications can be configured under
      :doc:`Channels > Email > Settings > Notification Sender <../settings>`.
```

2020-10-20 10:20 UTC, MrGeneration commented
No worries, thanks for having a look.
You're right, your approach is much better!

Is this ready to go from your end?

2020-10-21 05:31 UTC, rlue approved these changes
:100:

2020-10-22 12:52 UTC, merged